config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/cart_count', :to => 'store#cart_count', :as => :cart_count
  get '/help', :to => 'freshdesk/solutions#index', as: :help
  post '/contact', to: 'freshdesk/solutions#contact'
  get '/toggle_backorder_preference', to: 'checkout#update_backorder_preference', as: :toggle_backorder_preference

  post '/check_user_email', to: 'checkout#check_email', as: :checkout_check_email
  post '/assign_user_to_order', to: 'checkout#assign_user', as: :checkout_assign_user

  resources :stylesheets, only: :show

  namespace :admin do
    resources :stylesheets
  end

end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do

  alias_method :original_load_data, :load_data

  private

  def load_data
    @layouts = Spree::Product::LAYOUTS
    original_load_data
  end

end

app/controllers/spree/admin/stylesheets_controller.rb
module Spree
  module Admin
    class StylesheetsController < ResourceController
      update.before :set_stores

      def index
        @stylesheets = Spree::Stylesheet.all
      end

      private

      def permitted_stylesheets_attributes
        [:name, :banner_bg, :header_1_background_color, :header_1_color, :header_2_background_color,
         :header_2_color, :header_2_link_color, :product_background_color, :product_price_label_background_color,
         :product_price_label_color, :product_options_background_color, :product_options_option_background_color,
         :product_options_option_color, :layout_color_1, :layout_color_2, :layout_color_3, :leftnav_color_1,
         :leftnav_color_2, :leftnav_color_3, :layout_links_color, :logo, :banner, :hide_banner_text, {store_ids: []}]
      end

      def set_stores
        @stylesheet.store_ids = nil unless params[:stylesheet].key? :store_ids
      end
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do
  include Devise::Controllers::SignInOut

  skip_before_filter :check_registration, only: [:update, :edit, :check_email]

  def check_email
    raise "No order present" if @order.blank?
    @email = params[:user_email]
    @order.update_column :email, @email
    respond_to(&:js)
  end

  def assign_user
    raise "No order present" if @order.blank?
    return if @order.email.blank?

    pass = ->x{ params[x].is_a?(Array) ? params[x].first : params[x] }

    if pass[:password] && pass[:password_confirmation]
      @user = Spree::User.create(
        email: @order.email,
        password: pass[:password],
        password_confirmation: pass[:password_confirmation]
      )
    elsif pass[:password]
      @user = Spree::User.find_by(email: @order.email)

      unless @user && @user.valid_password?(pass[:password])
        @user = nil
      end
    end

    if @user && @user.persisted?
      sign_in @user and @order.update_column :user_id, @user.id
    end
  end

  # Updates the order and advances to the next state (when possible.)
  # (Slightly modified copy/paste from spree/spree)
  def update
    # Hold onto shipping rates by name if possible
    if params[:steps] && params[:steps].include?('delivery')
      @selected_rate_names = @order.shipments.map { |s| s.selected_shipping_rate.name }
    end

    if @order.update_from_params(params, permitted_checkout_attributes)
      persist_user_address
      unless @order.next
        flash[:error] = @order.errors.full_messages.join("\n")
        redirect_to_state and return
      end

      # Restore shipping rates by name if possible
      if @selected_rate_names
        @order.shipments.each_with_index do |shipment, i|
          rate = shipment.shipping_rates.find { |r| r.name == @selected_rate_names[i] }
          shipment.selected_shipping_rate_id = rate.id if rate
        end
        # Advance order state again since shipping has been selected already
        @order.next
      end

      if @order.completed?
        session[:order_id] = nil
        flash.notice = Spree.t(:order_processed_successfully)
        flash[:commerce_tracking] = "nothing special"
        checkout_complete
      else
        redirect_to_state
      end
    else
      render :edit
    end
  end

  def update_backorder_preference
    @order.update_attribute(:dont_split_packages_on_backorder, !@order.dont_split_packages_on_backorder)
    @order.create_proposed_shipments
    respond_to do |format|
      format.html do
        redirect_to checkout_state_path(:delivery), flash: {success: 'Successfully updated backorder preference' }    
      end
      format.js { params[:steps] = 'delivery' and render 'edit' }
    end
  end

  protected

  def redirect_to_state
    respond_to do |format|
      format.html { redirect_to checkout_state_path(@order.state) }
      format.js { render :edit }
    end
  end

  def checkout_complete
    respond_to do |format|
      format.html { redirect_to completion_route }
      format.js { @completion_route = "#{request.base_url}#{completion_route}"; render :complete }
    end
  end
end

app/controllers/spree/freshdesk/solutions_controller.rb
module Spree
  module Freshdesk
    class SolutionsController < Spree::StoreController
      before_filter :prepare_data


      def index

      end

      def show

      end

      def contact
        @result = create_support_ticket(params[:ticket])
        if @result == 'success'
          flash[:success] = 'Thank you for contacting support! One of our support staff team members will respond within the next business day.'
          redirect_to help_path
        else
          flash[:error] = @result
          redirect_to "#{help_path}", params
        end

      end

      private

      def create_support_ticket(ticket)
        return 'Sorry, you must enter your name to submit a support ticket' if params[:ticket][:name].blank?
        return 'Sorry, you must enter your e-mail to submit a support ticket' if params[:ticket][:email].blank?
        return 'Sorry, you must enter a message body to submit a support ticket' if params[:ticket][:body].blank?

        description = "
        Name: #{ticket[:name]}
        Order: #{ticket[:order]}
        Subject: #{ticket[:subject]}
          #{ticket[:body]}
        "

        params = {
            helpdesk_ticket: {
                description: description,
                subject: ticket[:subject],
                email: ticket[:email],
                priority: support_priorities[ticket[:subject]],
                status: 2,
                source: 2,
                ticket_type: 'Problem',
                custom_field: {
                    email_address_7483: ticket[:email],
                    order_number_7483: ticket[:order],
                    department_7483: 'Retail- Starkid'
                }
            }
        }

        begin
          if Spree::Freshdesk::Ticket.new(params)
            return 'success'
          end
        rescue ActiveRecord::RecordNotSaved
          return "Sorry, your support ticket was not submitted. Please contact us directly at support@annarbortees.com"
        end
      end

      def prepare_data
        @categories = Spree::Freshdesk::SolutionCategory.all
        @categories.reject! do |category|
          category.folders.reject!{|folder| folder['visibility'] != 1 }
          category.folders.count == 0
        end

        @articles = {}
        @categories.each do |category|
          category.folders.each do |folder|
            @articles[folder['id']] = Spree::Freshdesk::Article.all(category.id, folder['id'])
          end
        end

        @support_subjects = support_subjects
      end


      def support_subjects
         [
            'I need to change an item in my order',
            'I need to change my shipping details',
            'I need to change my shipping method',
            "My order hasn't arrived yet",
            'I received the wrong or a damaged item',
            "I'm missing something I ordered",
            'I need to return/exchange an order',
            "I'm having trouble using the website",
            'I have a general question about a product',
            'Other'
        ]
      end

      def support_priorities
        {
          "I need to change an item in my order" => 4,
          "I need to change my shipping details" => 4,
          "I need to change my shipping method" => 4,
          "My order hasn't arrived yet" => 2,
          "I received the wrong or a damaged item" => 3,
          "I'm missing something I ordered" => 3,
          "I need to return/exchange an order" => 2,
          "I'm having trouble using the website" => 3,
          "I have a general question about a product" => 1,
          "I have a question for StarKid" => 1,
          "Other" => 2
        }
      end

    end
  end
end

app/helpers/spree/base_helper_decorator.rb
require 'uri'

Spree::BaseHelper.class_eval do
  def order_predicted_shipments(order, shipping_address = nil)
    return order.shipments if !order.shipments.blank? && shipping_address.nil?

    if shipping_address
      order.shipping_address ||= Spree::Address.new
      order.shipping_address.firstname = shipping_address[:firstname]
      order.shipping_address.lastname = shipping_address[:lastname]
      order.shipping_address.address1 = shipping_address[:address1]
      order.shipping_address.address2 = shipping_address[:address2]
      order.shipping_address.city = shipping_address[:city]
      order.shipping_address.zipcode = shipping_address[:zipcode]
      order.shipping_address.phone = shipping_address[:phone]
      order.shipping_address.state_name = shipping_address[:state_name]
      order.shipping_address.alternative_phone = shipping_address[:alternative_phone]
      order.shipping_address.company = shipping_address[:company]
      order.shipping_address.state_id = shipping_address[:state_id]
      order.shipping_address.country_id = shipping_address[:country_id]
      order.shipping_address.save
    end

    begin
      shipments = Spree::Stock::Coordinator.new(order).packages.map(&:to_shipment)
      if shipments.empty?
        return shipments
      elsif order.state == 'address'
        return order.shipments if order.next
      end
      []
    rescue StandardError => _e
      order.shipping_address.destroy
      order.shipping_address = nil
      order.shipments = Spree::Stock::Coordinator.new(order).packages.map(&:to_shipment)
    end
  end

  def modify_order(order, attrs)
    attrs.each do |key, value|
      order.send("#{key}=", value)
    end
  end

  def theme_class(store)
    return 'default' if store.stylesheets.empty?
    return store.stylesheets.first.style_class unless store.stylesheets.empty?
  end

  def stylesheet_asset_path(store)
    if !Rails.application.config.action_controller.asset_host.blank? and defined? AssetSync
      key = Digest::SHA1.hexdigest current_store.stylesheets.first.updated_at.to_s
      return "/spree/stylesheets/#{current_store.stylesheets.first.id}-#{key}.css"
    else
      return stylesheet_path(current_store.stylesheets.first.id)
    end
  end

  def theme_logo_path(store)
    return store.stylesheets.first.logo.url unless store.stylesheets.empty? || store.stylesheets.first.logo.blank?
    return 'logo.png'
  end

  def pinterest_link_url(url, description)
    url =  url || ''; description = description || ''
    "http://pinterest.com/pin/create/button/?url=#{URI.encode(url)}&description=#{URI.encode(description)}"
  end

  def facebook_link_url(url)
    url =  url || ''
    "https://www.facebook.com/sharer/sharer.php?#{URI.encode(url)}"
  end

  def twitter_link_url(url, text, hashtag)
    url =  url || ''; text = text || ''; hashtag = hashtag || ''
    "https://twitter.com/intent/tweet?hashtags=#{URI.encode(hashtag)}&text=#{URI.encode(text)}&url=#{URI.encode(url)}"
  end

  def tumblr_link_url(url, name, description)
    url =  url || ''; name = name || ''; description = description || ''
    "http://www.tumblr.com/share/link?url=#{URI.encode(url)}&name=#{URI.encode(name)}&description=#{URI.encode(description)}"
  end

  def rich_pin_tags(product)
    tag("meta", property: 'og:title', content: product.name) +
        tag("meta", property: 'og:type', content: 'product') +
        tag("meta", property: 'og:price:amount', content: product.price) +
        tag("meta", property: 'og:price:currency', content: current_currency) +
        tag("meta", property: 'og:url', content: product_url) +
        tag("meta", property: 'og:description', content: product.description)+
        tag("meta", property: 'og:site_name', content: 'Ann Arbor T-Shirt Company')+
        tag("meta", property: 'og:availability', content: 'instock')
  end

  def variant_button_width(text)
    if text.length > 7
      '45%'
    else
      'inherit'
    end
  end

  def breadcrumbs(taxon = nil, product = nil)
    if String === product
      product = nil
    end
    crumbs = [content_tag(:li, link_to(current_store.name , store_home_path))]

    if(taxon || product || current_page?(products_path))

      session['last_crumb'] = taxon ? taxon.permalink : nil
      crumbs = [content_tag(:li, link_to(current_store.name , store_home_path))]

      if taxon
        crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor))) } unless taxon.ancestors.empty?
        if product
          crumbs << content_tag(:li, link_to(taxon.name , seo_url(taxon)))
          crumbs << content_tag(:li, content_tag(:span, product.name), class: 'active')
        else
          crumbs << content_tag(:li, content_tag(:span, taxon.name), class: 'active')
        end
      elsif product
        #crumbs << content_tag(:li, link_to(t('products') , products_path))
        crumbs << content_tag(:li, content_tag(:span, product.name), class: 'active')
      else
        crumbs << content_tag(:li, content_tag(:span, t('products')), class: 'active')
      end
    elsif current_page?('/cart')
      crumbs << content_tag(:li, content_tag(:span, t('shopping cart')), class: 'active')
    end
    content_tag(:ol, raw(crumbs.flatten.map{|li| li.mb_chars}.join), class:'breadcrumb')
  end

  def last_crumb_path
    plink = session['last_crumb']
    if plink && taxon = Spree::Taxon.find_by_permalink(plink)
      seo_url(taxon)
    else
      products_path
    end
  end

  def taxons_tree(root_taxon, current_taxon, max_level = 1)
    return '' if max_level < 1 || root_taxon.children.empty?
    content_tag :ul, class: 'taxons-list' do
      root_taxon.children.map do |taxon|
        css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
        content_tag :li, class: css_class do
          link_to(taxon.name, seo_url(taxon)) +
              taxons_tree(taxon, current_taxon, max_level - 1)
        end
      end.join("\n").html_safe
    end
  end

  def flash_messages(opts = {})
    opts[:ignore_types] = [:commerce_tracking].concat(Array(opts[:ignore_types]) || [])

    flash.each do |msg_type, text|
      unless opts[:ignore_types].include?(msg_type)
        concat(content_tag(:div, content_tag(:div, text, class: "container"), class: "flash #{msg_type}"))
      end
    end
    nil
  end

  def sanitize_id(value)
    value.gsub(/[^a-zA-Z0-9\-_]/, '-')
  end

  def thumbnail_image(product, options = {}, option_value = nil, style = :small)
    # TODO: This is a complete hack to get masonry working
    # Solves the problem addressed https://github.com/passy/angular-masonry/issues/4

    begin
      if option_value
        image = product.images.where(thumbnail: true, option_value_id: option_value.id).first
      else
        image = product.images.where(thumbnail: true).shuffle[0]
      end

      if !image
        image = product.images.first
      end

      # options[:style] = "min-height: #{thumbnail_min_height(image, 176)}px;"

      create_product_image_tag(image, product, options, style)

    rescue
      begin
        link_to( small_image(product, {itemprop: "image"}), url, :itemprop => 'url')
      rescue NameError
      end
    end
  end

  def ipsum
    %(Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
    magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
    deserunt mollit anim id est laborum.")
  end


  def backorder_details(variant)
    if variant.product.backorder_details.blank?
      return "The item you've selected is currently sold out. It is however"\
          " available for backorder, although no details have been specified at this time"
    else
      return variant.product.backorder_details
    end
  end

end

app/helpers/spree/checkout_helper_decorator.rb
Spree::CheckoutHelper.class_eval do

  def checkout_progress
    states = checkout_states
    items = states.map do |state|
      text = Spree.t("order_state.#{state}").titleize

      css_classes = []
      current_index = states.index(@order.state)
      state_index = states.index(state)

      if state_index < current_index
        css_classes << 'completed'
        text = link_to text, checkout_state_path(state)
      end

      css_classes << 'next' if state_index == current_index + 1
      css_classes << 'current' if state == @order.state
      css_classes << 'first' if state_index == 0
      css_classes << 'last' if state_index == states.length - 1
      # It'd be nice to have separate classes but combining them with a dash helps out for IE6 which only sees the last class
      content_tag('li', content_tag('span', text), class: css_classes.join(' '))
    end
    content_tag('ol', raw(items.join("\n")), class: 'progress-steps', id: "checkout-step-#{@order.state}")
  end
end

app/views/spree/checkout/_confirm.html.erb
<div class="panel panel-default" id="order_details" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="panel-body">
	<%= render :partial => 'spree/shared/order_details', :locals => { :order => @order } %>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= button_tag :class => 'btn btn-lg btn-success' do %>
      <%= Spree.t(:place_order) %> <i class="glyphicon glyphicon-circle-arrow-right"></i>
  <% end %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_delivery.html.erb
<%= hidden_field_tag 'steps', 'payment' %>

<div class="panel panel-default" id='shipping_method' data-hook>
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= Spree.t(:delivery) %>
      <%= link_to '#', id: 'reload-delivery-step' do %>
        <i class='glyphicon glyphicon-refresh'></i>
      <% end %>
    </h3>
  </div>
  <div class="panel-body" data-hook="shipping_method_inner">

  <% if form.object.line_items.map{|li| li.variant.on_backorder }.any?{|q| q > 0 } %>
      
    <div class="row clear shipping-method-backorder-form">
        <p class="alert alert-success">
          This shopping cart contains a backordered item. 
          <% if form.object.dont_split_packages_on_backorder? %>
            Your current preference is to wait on all items to become available to ship together in one shipment.
            <% link_to "Click to change your preference to shipping backordered items separately as they become available", '#', class: 'btn btn-danger wrap-btn' %>
          <% else %>
            Your current preference is to ship your backordered items separately as they become available. 
            <% link_to "Click to change your preference to shipping all items together after backordered items become available", '#', class: 'btn btn-danger wrap-btn' %>
          <% end %>
        </p> 
        <p class="text-center">
          <%= link_to toggle_backorder_preference_path, class: 'btn btn-danger wrap-btn', style: 'color: #fff' do %>
            <% if form.object.dont_split_packages_on_backorder? %>
              Click if you'd prefer to ship backordered items separately from the rest of your order. 
            <% else %>
              Click if you'd prefer all items to be shipped together after backordered items become available. 
            <% end %>
          <% end %>
        </p>  
    </div>
  
  <% end %>
    <div id="methods">
      <% if form.object.shipments.empty? && order_predicted_shipments(form.object).empty? %>
        Fill out your shipping address to view shipping rates
      <% end %>

      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h4 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h4>

          <table class="table stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <tr class="active">
                <th></th>
                <th align='left'><%= Spree.t(:item) %></th>
                <th><%= Spree.t(:qty) %></th>
                <th><%= Spree.t(:price) %></th>
              </tr>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h4 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h4>
          <ul class="list-group shipping-methods">

            <% if ship_form.object.shipping_rates.empty? %>

              <% if form.object.state == 'address' %>
                Fill in shipping address to see shipping options
              <% else %>
                Free shipping
              <% end %>

            <% else %>

              <% ship_form.object.shipping_rates.each do |rate| %>
                <li class="list-group-item shipping-method">
                  <label>
                    <%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
                    <span class="rate-name"><%= rate.name %></span>
                    <span class="badge rate-cost"><%= rate.display_cost %></span>
                  </label>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>

      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <h4><%= Spree.t(:shipping_instructions) %></h4>
        <%= form.text_area :special_instructions, :cols => 40, :rows => 4, :class => "form-control" %>
      </p>
    <% end %>
  </div>
</div>

<br />

app/views/spree/checkout/_email.html.erb
<div id='checkout-order-email' class='panel panel-default'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Email Address</h3>
  </div>

  <div class='panel-body'>
    <%= form_tag checkout_check_email_path, remote: true do %>
      <%= label_tag :user_email, "Email" %>
      <%= email_field_tag :user_email, '', class: 'form-control' %>
    <% end %>
  </div>
</div>

app/views/spree/checkout/_error.html.erb
<div class='alert alert-danger alert-dismissible order-errors' role='alert'>
  <button type='button' class='close' data-dismiss='alert' aria-lable='Close'>
    &times;
  </button>

  <% if field.to_s.strip == 'base' %>
    <h3>Unable to place order for the following reasons:</h3>
  <% else %>
    <h3><%= field %></h3>
  <% end %>
  <% if errors.respond_to?(:each) %>
    <ul>
      <% errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% else %>
    <%= errors %>
  <% end %>
</div>

app/views/spree/checkout/_new_user.html.erb
<div class="col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= Spree.t(:create_new_account) %></h3>
    </div>
    <div id="new-customer" class="panel-body" data-hook="login">
    <%= form_for @user, :as => :spree_user, :url => spree.registration_path(@user) do |f| %>
      <div data-hook="signup_inside_form">
        <%= render :partial => 'spree/shared/user_form', :locals => { :f => f } %>
        <p><%= f.submit Spree.t(:create), :class => 'btn btn-lg btn-success btn-block' %></p>
      </div>
    <% end %>
    <div class="text-center">
      <%= Spree.t(:or) %>
        <%= link_to Spree.t(:login_as_existing), spree.login_path %>
    </div>
    <div data-hook="login_extras"></div>
  </div>
</div>

app/views/spree/checkout/_password.html.erb
<div id='checkout-account-panel' class='panel panel-default'>
  <div class='panel-heading'>
    <h3 class='panel-title'>Account</h3>
  </div>

  <div class='panel-body'>
    <%= form_tag checkout_assign_user_path, remote: true, id: "checkout-assign-user-form" do %>
      <% if Spree::User.where(email: order.email).exists? %>
        <div><%= Spree.t(:already_have_an_account) %></div>
        <%= label_tag :password, 'Password', class: 'control-label' %>
        <%= password_field :password, '', class: 'form-control' %>
      <% else %>
        <div><%= Spree.t(:dont_have_an_account) %></div>
        <%= label_tag :password, 'Password',                      class: 'control-label' %>
        <%= password_field :password, '',                         class: 'form-control' %>
        <%= label_tag :password_confirmation, 'Confirm password', class: 'control-label' %>
        <%= password_field :password_confirmation, '',            class: 'form-control' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spree/checkout/_payment.html.erb
<%= hidden_field_tag 'steps', 'confirm' %>

<div class="panel panel-default" id="payment" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:payment_information) %></h3>
  </div>
  <div class="panel-body" data-hook="checkout_payment_step">

    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">Use an existing card on file</label>
        <br/>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">Use a new card / payment method</label>
      </div>

      <div id="existing_cards">
        <p class="field" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %></td>
                  <td><%= card.year %></td>
                  <td>
                    <%= radio_button_tag "existing_card", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <ul class="list-group" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
      <li class="list-group-item">
        <label>
          <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
          <%= Spree.t(method.name, :scope => :payment_methods, :default => method.name) %>
        </label>
      </li>
      <% end %>
    </ul>

    <ul class="nav" id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render :partial => "spree/checkout/payment/#{method.method_type}", :locals => { :payment_method => method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>

    <p class='field' data-hook='coupon_code'>
      <%= form.label :coupon_code %><br />
      <%= form.text_field :coupon_code, :class => 'form-control' %>
    </p>
  </div>
</div>

app/views/spree/checkout/_step.html.erb
<%= form_for order, url: update_checkout_path(step), html: { id: "checkout_form_#{step}", class: "checkout_form" }, remote: true do |f| %>
  <%= render step, form: f %>
<% end %>

app/views/spree/checkout/assign_user.js.erb
window.submitStepFrom($('#payment'));

app/views/spree/checkout/complete.js.erb
window.location.replace("<%= @completion_route %>");